#! /bin/bash

# Make My Board!

KB_CHARYBDIS=bastardkb/charybdis/3x6/v2/splinky_2
KB_KYRIA=splitkb/kyria/rev1
KB_REDOX=redox/rev1

CMD=qmk
ACTION=compile
KEYBOARD=
KEYMAP=struckmb
SIDE=left

while getopts 'fhk:lm:rs:t' opt; do
    case "$opt" in
    f)
        ACTION=flash
        ;;
    h)
        echo """
            -f      flash
            -h      show this help
            -k <kb> compile for keyboard <kb>
            -l      compile for left side (default)
            -m <km> use keymap <km> (default: struckmb)
            -r      compile for right side
            -t      test (just output commands)
"""
        exit
        ;;
    k)
        if [ "$OPTARG" = "bastardkb" ]; then
            KEYBOARD=$KB_CHARYBDIS
        elif [ "$OPTARG" = "charybdis" ]; then
            KEYBOARD=$KB_CHARYBDIS
        elif [ "$OPTARG" = "kyria" ]; then
            KEYBOARD=$KB_KYRIA
        elif [ "$OPTARG" = "redox" ]; then
            KEYBOARD=$KB_REDOX
        else
            KEYBOARD=${OPTARG}
        fi
        ;;
    l)
        SIDE=left
        ;;
    m)
        KEYMAP=${OPTARG}
        ;;
    r)
        SIDE=right
        ;;
    t)
        CMD=echo\ qmk
        ;;
    esac
done

if [ -z "$KEYBOARD" ]; then
    echo userspace-compile
    $CMD userspace-compile
elif [ "$KEYBOARD" = "cantor" -a "$ACTION" = "flash" ]; then
    echo "keyboard: ${KEYBOARD}, keymap: ${KEYMAP}, side: ${SIDE}"
    $CMD $ACTION -kb $KEYBOARD -km ${KEYMAP} -bl "dfu-util-split-${SIDE}"
else
    echo "keyboard: ${KEYBOARD}, keymap: ${KEYMAP}"
    $CMD $ACTION -kb $KEYBOARD -km ${KEYMAP}
    if [ "$KEYBOARD" = "cantor" ]; then
        rm cantor_$KEYMAP*
        echo "removed unusable firmware (use flash and select correct side)"
    fi
fi
